travis:
  secure:
    BINSTAR_TOKEN: WHxM5mc5ESfFt+2sbnYItZ5DsqxzcwxxJfgxuS51CjU2+FHbObHk6xbebtFU/pMV4kWHdIcMjNKnZZToXqvu3tZT1ndPIKHH6f20omHXam4G8H80QApGwm5la5hqTtIAGf0OKJ2OTqpTL66S3IMcsjg+tucWe0F7lq2B2R7nHQEkEBNYRsdAuLXh8fn8Qn6I40Pks+0bTmI9rN0BBzpeppr69hVFfDXX4H4jQGyNfyS7/p4/u3e/dB/MHZqG9CGW+vsO3DtKKcLPK8WwSzrUJbszioR1yX7lN4AjHpw+Gp2MS0GaZnMajp8li5tlqXkwUOqkNUBgkWUlRE5xcTQjaxJ3u92hZrRnPSVriw6mwPoIGlpbr4QvIHFwhmDDPX22K83lFGkauIl2j6P1w1FVMgYktg3jTLm1sRQgn9xoIaJy8xMeSqmsZDg69KrZeg4eRQy0PQAdWIrY5mIKPZ5sKT1HbQlmjldEQbhLeYI7Vwg+hEzcsqiwew3m5hfSLN3MjpR9tVeZmKvl3sLLxEfEk3bsxoVuY3eJIcQA5XZn3EnBzkG4F3G62ahxtZNFmDGzfKtPVgQCNfyWYsWNjzact9+KASSQ8KdnVGVVVf7MmXW73aE58bnXLc1vJj4jurohoZ81El30DhmcaH+tOjDb0KJyFkFVUtmLPcvA4zBwXK0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
